### ISSUE TITLE
issue with parse_file and parse_url with .soi extension

### ISSUE THREAD

**Issue by amrit19** [PrefLib/preflibtools#4]
In the code below I am trying to read a file of the irish dataset of extension soi and am facing the following error:-

Exception has occurred: TypeError
File extension soi is not valid for this type of PrefLib instance. This file cannot be parsed.
    instance.parse_url("https://www.preflib.org/static/data/irish/00001-00000001.soi")
TypeError: File extension soi is not valid for this type of PrefLib instance. This file cannot be parsed.

`from preflibtools.instances import PrefLibInstance
instance = PrefLibInstance()
instance.parse_file("00001-00000001.soi")
instance.parse_url("https://www.preflib.org/static/data/irish/00001-00000001.soi")
for alt, alt_name in instance.alternatives_name.items():
    alternative = alt
    name = alt_name
    print("The alternative is=", alternative, "and the alternative name is=", name)
print("The number of voters=",instance.num_voters)

`
Do I have to do anything differently?

**Comment by amrit19** [comment]
However, if I import from OrdinalInstance as follows:-
from preflibtools.instances import OrdinalInstance
instance = OrdinalInstance()
instance.parse_file("00001-00000001.soi")

It works fine. Can we not import a general PrefLibInstance?

**Comment by Simon-Rey** [comment]
This is the intended behaviour, PreflibInstances is meant to be an abstract class and should not be used. I now realise that the information in the usage section of the doc was wrong. I've updated it.  Note that we provide the function `get_parsed_instance(file_path)` that will return an instance of the correct type, already parsed.
